In [16]:
# 실습 패키지
from sklearn.datasets import load_boston

# 기계학습 모델 구축 및 평가 패키지

import scipy as sp
import scipy.stats as stats

import statsmodels.api as sm
from statsmodels.formula.api import ols

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# 데이터 시각화 패키지

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 한글 폰트 설정

plt.rc('font',family = 'Malgun Gothic')


In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action="ignore")

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mpl
mpl.rcParams["axes.unicode_minus"] = False

import tensorflow as tf

import warnings
warnings.filterwarnings(action="ignore")

import keras
from keras.models import Sequential, load_model
from keras.layers.core import Dense
from keras.utils import np_utils
from keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import RMSprop, Adam, SGD

In [18]:
import tensorflow as tf

In [33]:
import tensorflow as tf

텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([3,4,5])

tf.add(텐서,텐서2)

텐서3 =tf.zeros([2,2,3]) # 3개를 담은 2개를 2개생성시켜주세요 뒤부터
print(텐서3)

print(텐서3.shape)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)
(2, 2, 3)


In [34]:
w = tf.Variable(1.0)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [35]:
# 데이터 불러오기
df = pd.read_csv("../pythonwork/ai/data/data1/train.csv")

In [36]:
df =df.drop('Cabin', axis=1)

In [37]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


In [38]:
df['Sex'] = df['Sex'].map({'male':0, 'female':1})

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Embarked  
0         A/5 21171   7.2500        S  
1          PC 17599  71.2833        C  
2  STON/O2. 3101282   7.9250        S  
3            113803  53.1000        S  
4            373450   8.0500        S

In [55]:
df =df.dropna()

df

df.isnull().sum()

df.describe()

PassengerId    Survived      Pclass         Sex         Age  \
count   712.000000  712.000000  712.000000  712.000000  712.000000   
mean    448.589888    0.404494    2.240169    0.363764   29.642093   
std     258.683191    0.491139    0.836854    0.481420   14.492933   
min       1.000000    0.000000    1.000000    0.000000    0.420000   
25%     222.750000    0.000000    1.000000    0.000000   20.000000   
50%     445.000000    0.000000    2.000000    0.000000   28.000000   
75%     677.250000    1.000000    3.000000    1.000000   38.000000   
max     891.000000    1.000000    3.000000    1.000000   80.000000   

            SibSp       Parch        Fare  
count  712.000000  712.000000  712.000000  
mean     0.514045    0.432584   34.567251  
std      0.930692    0.854181   52.938648  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    8.050000  
50%      0.000000    0.000000   15.645850  
75%      1.000000    1.000000   33.000000  
max      5.000000    6.000000  512.329200

In [40]:
y = df['Survived'].values

print(y)


[0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0
 0 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0
 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1
 0 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 1 0 1 0 0 1
 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0
 0 1 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1
 1 1 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0
 0 0 0 1 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 1
 1 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1 0 0
 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 1
 1 0 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1 1
 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1
 0 0 1 0 0 1 0 0 1 1 0 0 

In [41]:
x = []

for i, rows in df.iterrows():
    x.append([rows['Fare'],rows['Age'],rows['Pclass'],rows['Sex']]) # 요금 나이 등급
    
print(x)

[[7.25, 22.0, 3, 0], [71.2833, 38.0, 1, 1], [7.925, 26.0, 3, 1], [53.1, 35.0, 1, 1], [8.05, 35.0, 3, 0], [51.8625, 54.0, 1, 0], [21.075, 2.0, 3, 0], [11.1333, 27.0, 3, 1], [30.0708, 14.0, 2, 1], [16.7, 4.0, 3, 1], [26.55, 58.0, 1, 1], [8.05, 20.0, 3, 0], [31.275, 39.0, 3, 0], [7.8542, 14.0, 3, 1], [16.0, 55.0, 2, 1], [29.125, 2.0, 3, 0], [18.0, 31.0, 3, 1], [26.0, 35.0, 2, 0], [13.0, 34.0, 2, 0], [8.0292, 15.0, 3, 1], [35.5, 28.0, 1, 0], [21.075, 8.0, 3, 1], [31.3875, 38.0, 3, 1], [263.0, 19.0, 1, 0], [27.7208, 40.0, 1, 0], [10.5, 66.0, 2, 0], [82.1708, 28.0, 1, 0], [52.0, 42.0, 1, 0], [8.05, 21.0, 3, 0], [18.0, 18.0, 3, 1], [11.2417, 14.0, 3, 1], [9.475, 40.0, 3, 1], [21.0, 27.0, 2, 1], [41.5792, 3.0, 2, 1], [7.8792, 19.0, 3, 1], [17.8, 18.0, 3, 1], [39.6875, 7.0, 3, 0], [7.8, 21.0, 3, 0], [76.7292, 49.0, 1, 1], [26.0, 29.0, 2, 1], [61.9792, 65.0, 1, 0], [10.5, 21.0, 2, 1], [7.2292, 28.5, 3, 0], [27.75, 5.0, 2, 1], [46.9, 11.0, 3, 0], [7.2292, 22.0, 3, 0], [83.475, 45.0, 1, 0], [27.9,

In [42]:
###텐서 플로우 안에 케라스를쓰면 딥러닝이 쉬워진다... w1,w2이런거구하기쉬움
# activation 활성 함수는 내마음대로
# sigmoid는 0~1에서 확률을 뱉고싶을때 쓰는함수


#1. 모델 디자인
# 히든 레이어 1,2,3 개쓴거임 지금

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation='tanh'),   #히든레이어임 이게...
    tf.keras.layers.Dense(256, activation='tanh'),  # 노드의 갯수 64,128,1개 동그란거갯수
    tf.keras.layers.Dense(1, activation='sigmoid'), #마지막에는 하나의 노드가 되어야함..
])


# 2. model complie 하기 # ?? 파라미터(매개변수) 넣기
# binary_crossentropy 0~1사이에서 확률문제에서 씀

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# model.fit(x데이터,y데이터, epochs=10)

model.fit(np.array(x),np.array(y), epochs=1000) # test값 x


Epoch 1/1000
23/23 [==============================] - 1s 3ms/step - loss: 0.6719 - accuracy: 0.6573
Epoch 2/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.6206 - accuracy: 0.6573
Epoch 3/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.6015 - accuracy: 0.6868
Epoch 4/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.6084 - accuracy: 0.6938
Epoch 5/1000
23/23 [==============================] - 0s 4ms/step - loss: 0.5790 - accuracy: 0.6854
Epoch 6/1000
23/23 [==============================] - 0s 4ms/step - loss: 0.5810 - accuracy: 0.6896
Epoch 7/1000
23/23 [==============================] - 0s 4ms/step - loss: 0.5693 - accuracy: 0.7149
Epoch 8/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.5533 - accuracy: 0.7303
Epoch 9/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.5367 - accuracy: 0.7346
Epoch 10/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.5152 - accuracy: 0.7654

23/23 [==============================] - 0s 3ms/step - loss: 0.3976 - accuracy: 0.8244
Epoch 83/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.4045 - accuracy: 0.8357
Epoch 84/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.4120 - accuracy: 0.8118
Epoch 85/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3967 - accuracy: 0.8357
Epoch 86/1000
23/23 [==============================] - 0s 4ms/step - loss: 0.4174 - accuracy: 0.8272
Epoch 87/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.4147 - accuracy: 0.8188
Epoch 88/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8090
Epoch 89/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3971 - accuracy: 0.8272
Epoch 90/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3944 - accuracy: 0.8329
Epoch 91/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.4245 - accuracy: 0.7921
Epoc

23/23 [==============================] - 0s 2ms/step - loss: 0.3688 - accuracy: 0.8371
Epoch 163/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3790 - accuracy: 0.8455
Epoch 164/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3677 - accuracy: 0.8371
Epoch 165/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3900 - accuracy: 0.8258
Epoch 166/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3726 - accuracy: 0.8497
Epoch 167/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3716 - accuracy: 0.8399
Epoch 168/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3739 - accuracy: 0.8441
Epoch 169/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3658 - accuracy: 0.8441
Epoch 170/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3674 - accuracy: 0.8497
Epoch 171/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3674 - accuracy: 0.

23/23 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8497
Epoch 243/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3549 - accuracy: 0.8483
Epoch 244/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3709 - accuracy: 0.8301
Epoch 245/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3603 - accuracy: 0.8511
Epoch 246/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3459 - accuracy: 0.8581
Epoch 247/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8483
Epoch 248/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 0.8581
Epoch 249/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3519 - accuracy: 0.8371
Epoch 250/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3614 - accuracy: 0.8525
Epoch 251/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3585 - accuracy: 0.

23/23 [==============================] - 0s 3ms/step - loss: 0.3538 - accuracy: 0.8567
Epoch 323/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3279 - accuracy: 0.8708
Epoch 324/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3268 - accuracy: 0.8610
Epoch 325/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3497 - accuracy: 0.8511
Epoch 326/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3396 - accuracy: 0.8652
Epoch 327/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3296 - accuracy: 0.8708
Epoch 328/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3366 - accuracy: 0.8624
Epoch 329/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8581
Epoch 330/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8736
Epoch 331/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.

23/23 [==============================] - 0s 3ms/step - loss: 0.3261 - accuracy: 0.8624
Epoch 403/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8596
Epoch 404/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3282 - accuracy: 0.8624
Epoch 405/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3162 - accuracy: 0.8581
Epoch 406/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3134 - accuracy: 0.8666
Epoch 407/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3163 - accuracy: 0.8736
Epoch 408/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3116 - accuracy: 0.8806
Epoch 409/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3194 - accuracy: 0.8624
Epoch 410/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3272 - accuracy: 0.8638
Epoch 411/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3147 - accuracy: 0.

23/23 [==============================] - 0s 2ms/step - loss: 0.3122 - accuracy: 0.8652
Epoch 483/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3050 - accuracy: 0.8820
Epoch 484/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3149 - accuracy: 0.8610
Epoch 485/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3021 - accuracy: 0.8792
Epoch 486/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3133 - accuracy: 0.8722
Epoch 487/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3130 - accuracy: 0.8792
Epoch 488/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3080 - accuracy: 0.8750
Epoch 489/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3007 - accuracy: 0.8806
Epoch 490/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3177 - accuracy: 0.8708
Epoch 491/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.3034 - accuracy: 0.

23/23 [==============================] - 0s 2ms/step - loss: 0.2976 - accuracy: 0.8764
Epoch 563/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2982 - accuracy: 0.8820
Epoch 564/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2952 - accuracy: 0.8736
Epoch 565/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3027 - accuracy: 0.8764
Epoch 566/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2964 - accuracy: 0.8806
Epoch 567/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3034 - accuracy: 0.8666
Epoch 568/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2975 - accuracy: 0.8666
Epoch 569/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3014 - accuracy: 0.8876
Epoch 570/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2932 - accuracy: 0.8876
Epoch 571/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.3029 - accuracy: 0.

23/23 [==============================] - 0s 2ms/step - loss: 0.2868 - accuracy: 0.8848
Epoch 642/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.2860 - accuracy: 0.8736
Epoch 643/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2886 - accuracy: 0.8806
Epoch 644/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2973 - accuracy: 0.8722
Epoch 645/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2908 - accuracy: 0.8792
Epoch 646/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.2831 - accuracy: 0.8834
Epoch 647/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.2856 - accuracy: 0.8764
Epoch 648/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2947 - accuracy: 0.8792
Epoch 649/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2896 - accuracy: 0.8764
Epoch 650/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2956 - accuracy: 0.

23/23 [==============================] - 0s 2ms/step - loss: 0.2679 - accuracy: 0.8806
Epoch 722/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2747 - accuracy: 0.8862
Epoch 723/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2712 - accuracy: 0.8904
Epoch 724/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2816 - accuracy: 0.8834
Epoch 725/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2742 - accuracy: 0.8820
Epoch 726/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2809 - accuracy: 0.8848
Epoch 727/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2765 - accuracy: 0.8834
Epoch 728/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2725 - accuracy: 0.8806
Epoch 729/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2692 - accuracy: 0.8834
Epoch 730/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.2698 - accuracy: 0.

23/23 [==============================] - 0s 3ms/step - loss: 0.2588 - accuracy: 0.8890
Epoch 802/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2655 - accuracy: 0.8806
Epoch 803/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2638 - accuracy: 0.8890
Epoch 804/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2725 - accuracy: 0.8834
Epoch 805/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2596 - accuracy: 0.8876
Epoch 806/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2631 - accuracy: 0.8848
Epoch 807/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2640 - accuracy: 0.8890
Epoch 808/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2717 - accuracy: 0.8764
Epoch 809/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2605 - accuracy: 0.8876
Epoch 810/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2602 - accuracy: 0.

23/23 [==============================] - 0s 2ms/step - loss: 0.2472 - accuracy: 0.8989
Epoch 882/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2567 - accuracy: 0.8904
Epoch 883/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2504 - accuracy: 0.8933
Epoch 884/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2504 - accuracy: 0.8919
Epoch 885/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2586 - accuracy: 0.8834
Epoch 886/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2583 - accuracy: 0.8890
Epoch 887/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.2486 - accuracy: 0.8904
Epoch 888/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2483 - accuracy: 0.8989
Epoch 889/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2551 - accuracy: 0.8890
Epoch 890/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2573 - accuracy: 0.

23/23 [==============================] - 0s 2ms/step - loss: 0.2437 - accuracy: 0.8919
Epoch 962/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.2474 - accuracy: 0.8890
Epoch 963/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2452 - accuracy: 0.9003
Epoch 964/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2528 - accuracy: 0.8876
Epoch 965/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2575 - accuracy: 0.8919
Epoch 966/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2510 - accuracy: 0.8806
Epoch 967/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2423 - accuracy: 0.8961
Epoch 968/1000
23/23 [==============================] - 0s 3ms/step - loss: 0.2390 - accuracy: 0.8961
Epoch 969/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2436 - accuracy: 0.8961
Epoch 970/1000
23/23 [==============================] - 0s 2ms/step - loss: 0.2467 - accuracy: 0.

In [54]:
# 예측 
# 요금,나이,객실등급,성별: 1여자 0남자

pr = model.predict([[15,22,3,1],[15,29,3,0]])
print(pr)

#즉 티켓의 요금이 높고 어리고 높은등급객실에 여자가 살 확률이 존나게 높다.

[[0.80906296]
 [0.00796366]]
